name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Fixed cron syntax with 5 asterisks
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}  # Keep this since you're using PAT
      
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SharaFigueredo
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Keep using PAT here as well
